stages:
  - lint
  - test

cache:
  paths:
    - .cache/pip

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

pylint:
  stage: lint
  image: python:3.12-slim
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pylint pylint-django
  script:
    - export DJANGO_SETTINGS_MODULE=main.settings
    - pylint ep_files_app/ main/ --load-plugins=pylint_django --django-settings-module=main.settings --disable=C0114,C0115,C0116,C0103,R0903,C0303,C0411,C0412
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "dev"'

pytest:
  stage: test
  image: python:3.12-slim
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pytest pytest-django
  script:
    - pytest || echo "No tests yet"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "dev"'