stages:
  - lint
  - test

install-deps:
  stage: lint
  image: python:3.12-slim
  script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - .pip-cache/

pylint:
  stage: lint
  image: python:3.12-slim
  before_script:
    - pip install pylint pylint-django
  script:
    - pylint ep_files_app/ main/ --score=yes --load-plugins=pylint_django
  allow_failure: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "dev"'

pytest:
  stage: test
  image: python:3.12-slim
  before_script:
    - pip install pytest pytest-django -r requirements.txt
  script:
    - pytest ep_files_app/ tests/ --verbose || echo "No tests yet"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "dev"'
