FROM python:3.13-slim

WORKDIR /app

# Системные зависимости (нужны для python-magic и Pillow)
RUN apt-get update && apt-get install -y \
    libmagic1 \
    libjpeg-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Зависимости Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект
COPY . .

# Создаём нужные папки
RUN mkdir -p /app/logs /app/storage

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
