# Generated by Django 4.2.11 on 2026-05-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep_files_app', '0003_alter_file_id_alter_user_id_folder_file_folder'),
        ('ep_files_app', '0003_filehistory'),
    ]

    operations = [
    ]
