# Generated by Django 4.2.11 on 2026-05-10 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep_files_app', '0004_merge_20260507_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('read', 'Чтение'), ('read_write', 'Чтение и запись')], default='read', help_text='Тип прав доступа', max_length=20)),
                ('inherit', models.BooleanField(default=True, help_text='Наследовать права на вложенные файлы и папки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='filehistory',
            new_name='ep_files_ap_file_id_1c9eee_idx',
            old_name='ep_files_ap_file_id_b8c9e5_idx',
        ),
        migrations.RenameIndex(
            model_name='filehistory',
            new_name='ep_files_ap_user_id_bea199_idx',
            old_name='ep_files_ap_user_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='filehistory',
            new_name='ep_files_ap_event_t_822793_idx',
            old_name='ep_files_ap_event_t_d4e5f6_idx',
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='permission',
            name='file',
            field=models.ForeignKey(blank=True, help_text='Файл, к которому выдаются права', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='ep_files_app.file'),
        ),
        migrations.AddField(
            model_name='permission',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Папка, к которой выдаются права', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='ep_files_app.folder'),
        ),
        migrations.AddField(
            model_name='permission',
            name='granted_by',
            field=models.ForeignKey(help_text='Пользователь, выдавший права', on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, получающий права доступа', on_delete=django.db.models.deletion.CASCADE, related_name='received_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['user', 'file'], name='ep_files_ap_user_id_c3a0de_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['user', 'folder'], name='ep_files_ap_user_id_474419_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['file'], name='ep_files_ap_file_id_a04628_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['folder'], name='ep_files_ap_folder__07eed6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('user', 'file'), ('user', 'folder')},
        ),
    ]
