# Generated by Django 4.2.11 on 2026-05-17 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep_files_app', '0007_alter_file_id_alter_filehistory_id_alter_folder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favored_by', to='ep_files_app.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ep_files_app_favorite_file',
                'unique_together': {('user', 'file')},
            },
        ),
    ]
