# Generated by Django 4.2.11 on 2026-05-17 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ('ep_files_app', '0007_alter_file_id_alter_filehistory_id_alter_folder_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritefile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favoritefile',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ep_files_app.file'),
        ),
        migrations.AlterField(
            model_name='favoritefile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
